In [46]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
ratings = pd.read_csv("../data/rating.csv")
movies = pd.read_csv("../data/movie.csv")

In [7]:
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [8]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
ratings.shape, movies.shape

((20000263, 4), (27278, 3))

In [16]:
ratings['movieId'].nunique(),ratings['userId'].nunique(),movies['movieId'].nunique()

(26744, 138493, 27278)

In [17]:
df = pd.merge(ratings, movies, on=['movieId'])

In [18]:
df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [20]:
df['title'].value_counts().head(10)

title
Pulp Fiction (1994)                          67310
Forrest Gump (1994)                          66172
Shawshank Redemption, The (1994)             63366
Silence of the Lambs, The (1991)             63299
Jurassic Park (1993)                         59715
Star Wars: Episode IV - A New Hope (1977)    54502
Braveheart (1995)                            53769
Terminator 2: Judgment Day (1991)            52244
Matrix, The (1999)                           51334
Schindler's List (1993)                      50054
Name: count, dtype: int64

In [24]:
df.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
title        0
genres       0
dtype: int64

In [25]:
df.to_csv("../data/finalData.csv")

In [29]:
movies_stats = df.groupby('title').agg({'rating': ['mean', 'count']})

In [30]:
movies_stats.columns = ['avg_rating', 'num_rating']
movies_stats = movies_stats.reset_index()

In [31]:
movies_stats.head()

                                               title  avg_rating  num_rating
0  #chicagoGirl: The Social Network Takes on a Di...    3.666667           3
1                                 $ (Dollars) (1971)    2.833333          24
2                                    $5 a Day (2008)    2.871795          39
3                                       $9.99 (2008)    3.009091          55
4                     $ellebrity (Sellebrity) (2012)    2.000000           2

In [33]:
popular_movies = movies_stats[movies_stats['num_rating'] > 100]
popular_movies

                                           title  avg_rating  num_rating
10                        'Round Midnight (1986)    3.615385         182
11                           'Salem's Lot (2004)    3.111538         130
12                     'Til There Was You (1997)    2.847115         520
14                            'burbs, The (1989)    3.067391        3220
15                          'night Mother (1986)    3.449153         354
...                                          ...         ...         ...
26712                            eXistenZ (1999)    3.333428        5298
26716                                 xXx (2002)    2.798437        4542
26717             xXx: State of the Union (2005)    2.323415         773
26720                      ¡Three Amigos! (1986)    3.096299        6485
26723  À nous la liberté (Freedom for Us) (1931)    3.656977         172

[8531 rows x 3 columns]

In [41]:
popular_movies = popular_movies.sort_values(by='avg_rating', ascending=False)

def getPopularMovies(n=10):
    return popular_movies.head(n)

In [42]:
getPopularMovies()

                                               title  avg_rating  num_rating
20779               Shawshank Redemption, The (1994)    4.446990       63366
9586                           Godfather, The (1972)    4.364732       41355
24967                     Usual Suspects, The (1995)    4.334372       47006
20317                        Schindler's List (1993)    4.310175       50054
9587                  Godfather: Part II, The (1974)    4.275641       27398
20600    Seven Samurai (Shichinin no samurai) (1954)    4.274180       11611
19203                             Rear Window (1954)    4.271334       17449
2072                         Band of Brothers (2001)    4.263182        4305
4236                               Casablanca (1942)    4.258327       24349
22420  Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)    4.256935        6525

In [43]:
movies['genres'] = movies['genres'].str.replace('|', ' ')

In [44]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
tfidf = TfidfVectorizer()
tfid_matrix = tfidf.fit_transform(movies['genres'])

In [ ]:
similarity = cosine_similarity(tfid_matrix)